name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-test:
    name: Lint, type-check, and test (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13"]
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONUNBUFFERED: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      QT_QPA_PLATFORM: offscreen
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libx11-xcb1 \
            libxkbcommon-x11-0 \
            libxcb1 \
            libxcb-render0 \
            libxcb-shm0 \
            libxcb-xfixes0 \
            libxext6 \
            libxrender1 \
            libxrandr2 \
            libxi6 \
            libegl1 \
            libopengl0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest coverage mypy ruff

      # Cross-platform clean to avoid mypy duplicate modules
      - name: Clean build artifacts (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build, dist -ErrorAction SilentlyContinue

      - name: Clean build artifacts (POSIX)
        if: runner.os != 'Windows'
        run: |
          rm -rf build/ dist/ || true

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Type check (mypy)
        run: python -m mypy .

      - name: Run tests with coverage (Linux via xvfb)
        if: runner.os == 'Linux'
        run: |
          xvfb-run -a coverage run -m pytest -q
          coverage xml

      - name: Run tests with coverage (macOS/Windows)
        if: runner.os != 'Linux'
        run: |
          coverage run -m pytest -q
          coverage xml

      - name: Upload coverage to Codecov (optional)
        if: ${{ success() && env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ env.CODECOV_TOKEN }}
