name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-test:
    name: Lint, type-check, and test (Windows, py${{ matrix.python-version }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONUNBUFFERED: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      QT_QPA_PLATFORM: offscreen
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Cross-platform clean to avoid mypy duplicate modules (Windows-only)
      - name: Clean build artifacts (Windows)
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build, dist -ErrorAction SilentlyContinue

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Type check (mypy)
        run: python -m mypy .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest -q
          coverage xml

      - name: Upload coverage to Codecov (optional)
        if: ${{ success() && env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ env.CODECOV_TOKEN }}
